### ISSUE TITLE
Use decl_error macro for doughnut error codes

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#10]
Refactor error codes in `PlugDoughnut` with the `decl_error!` macro 

Here:
https://github.com/plugblockchain/plug-blockchain/blob/e57ff013d33197899807aab94793ffbb575b0562/prml/doughnut/src/impls.rs#L117-L124

Reference usage in srml/system:
https://github.com/plugblockchain/plug-blockchain/blob/e57ff013d33197899807aab94793ffbb575b0562/srml/system/src/lib.rs#L331-L340

**Comment by cowboy-bebug** [comment]
Signature of `SignedExtension::validate()` is like this:
https://github.com/plugblockchain/plug-blockchain/blob/3d533cf343484ad56d18135e84338b51942a3646/core/sr-primitives/src/traits.rs#L692-L698

https://github.com/plugblockchain/plug-blockchain/blob/3d533cf343484ad56d18135e84338b51942a3646/core/sr-primitives/src/transaction_validity.rs#L162

This task may require modifying the above signature

**Comment by jordy25519** [comment]
Closing as invalid
