### ISSUE TITLE
Create / refactor Dockerfile

### ISSUE THREAD

**Issue by cowboy-bebug** [plugblockchain/plug-blockchain#12]
To make the docker image work with our deployment pipeline (k8s), we need `ENTRYPOINT` instead of `COMMAND`. There are also two conflicting Dockerfiles:
- [./Dockerfile](https://github.com/plugblockchain/plug-blockchain/blob/develop/Dockerfile) <- this seems to be the active dev one
- [./scripts/docker/substrate.Dockerfile](https://github.com/plugblockchain/plug-blockchain/blob/develop/scripts/docker/substrate.Dockerfile) <- the above may get refactored into this file later (but I'm not sure what they will do)

Task list:
- [ ] Refactor dockerfile
- [ ] Update changelog

**Comment by jordy25519** [comment]
Both those Dockerfiles come from substrate. The image on dockerhub is built from https://github.com/plugblockchain/plug-blockchain/blob/develop/Dockerfile

It can be updated to use `ENTRYPOINT` _if_ needed, though it should possible to use the image properly already without the change and use the config on the helm/k8s side

e.g. `docker run plugnet/plugblockchain:1.0.0-rc1 substrate --dev` works well enough

**Comment by cowboy-bebug** [comment]
It should work by not specifying `command`.
