### ISSUE TITLE
Invulnerables (HotFix)

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#16]
As a node operator I want some network peers to be invulnerable to the reputation system so that my network is less volatile.

Tasks:
- [x] Make a branch from cennznet/plug-blockchain ~`9d72ac28731d2dbf558f21683d17bd4f799213ca`~ `stable` for the hotfix work

- [x] Change  `on_report_peer` behavior so that reserved node connections are not dropped
https://github.com/plugblockchain/plug-blockchain/blob/9d72ac28731d2dbf558f21683d17bd4f799213ca/core/peerset/src/lib.rs#L261

- [x] Write integration tests to mock CENNZnet Rimu network structure
https://github.com/plugblockchain/plug-blockchain/tree/develop/core/network/src/test

- [x] __A/C__ Hotfix deployed by SREs into CENNZnet Rimu network

**Comment by mzxyz** [comment]
Start working on the first 2 tasks

**Comment by hoani** [comment]
Investigated the reputation mechanism. Came to the conclusion that reputation is not broadcast, therefore a unit test is adequate.

**Comment by cowboy-bebug** [comment]
Yeah I think it makes sense for each node to keep its own local copy of the ranking / reputation (because different nodes probably have different reputation for the same peer)
