### ISSUE TITLE
Fix conflicting impl of Decode for RuntimeDispatchInfo

### ISSUE THREAD

**Issue by aliXsed** [plugblockchain/plug-blockchain#180]
The previous solution to https://github.com/cennznet/cennznet/issues/341 which was https://github.com/plugblockchain/plug-blockchain/pull/163 had to be reverted after merging the latest upstream due to causing a conflict in impl of Decode for RuntimeDispatchInfo. 
We need to find a different solution or adjust the current one with the latest changes.

**Comment by jordy25519** [comment]
there's a fix here: https://github.com/plugblockchain/plug-blockchain/blob/2bb930d6a0c003a18ddb99bd6b70287afd0669f8/frame/transaction-payment/src/types.rs
