### ISSUE TITLE
Leave account storage handling in Generic Asset to an account store

### ISSUE THREAD

**Issue by aliXsed** [plugblockchain/plug-blockchain#181]
The study of recent upstream changes suggests to me that our generic asset module which is replacing the balances pallet should use an account store when dealing with creating or removing accounts. An account store will be bound to `StoredMap` and its functionalities is already implemented by `frame_system::Module`. The generic asset should only call functions like `insert` or `try_mutate_exists` when appropriate.

**Comment by jordy25519** [comment]
an update on this, the account store doesn't need to track balances at this stage but we have the API to support account existence checks in wider system/frame context
