### ISSUE TITLE
Generic asset does not allow system account reaping

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#189]
When used to provide `AccountData` to system pallet generic asset will always act as a "provider" for the account, even after all it's balance related storage has been reclaimed.

This prevents the system module from reclaiming the account storage e.g. current nonce.
For now this is the safest behaviour as removing an account's nonce has it's own set of challenges.

Issue opened here to track the behaviour.

**Comment by aliXsed** [comment]
Closing it as it was addressed in https://github.com/plugblockchain/plug-blockchain/pull/186
