### ISSUE TITLE
Stability Testing Script

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#24]
The script should should send continual extrinsics to a plug network under test.

It should add random variance to:
- the type of extrinsic (balance transfer, attestation, etc.)
- sender account
- transaction rate (TPS)

It should stop after significant non-responsiveness by the network which would indicate a failure **or** a target block height is reached by majority of the nodes.

A/C - script demonstrated working on local plug development network running `1.0.0-rc.1`

Should make use of https://github.com/plugblockchain/plug-sdk-types

**Comment by hoani** [comment]
Additional notes from discussion with Jordy:
Add argument for exit condition - this should be based on a  final block height
Add argument for the time between transactions (can be done later)
Transactions should be random between alice/bob/charlie

**Comment by jordy25519** [comment]
closed via https://github.com/plugblockchain/plug-load-test
