### ISSUE TITLE
Fix compilation warnings

### ISSUE THREAD

**Issue by aliXsed** [plugblockchain/plug-blockchain#26]
warning: unused import: `contracts_rpc_runtime_api::ContractExecResult`
  --> node/runtime/src/lib.rs:52:5
   |
52 | use contracts_rpc_runtime_api::ContractExecResult;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `StorageMap`
  --> core/test-runtime/src/system.rs:22:38
   |
22 | use runtime_support::storage::{self, StorageMap};
   |                                      ^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

**Comment by jordy25519** [comment]
closed via #99
