### ISSUE TITLE
Initial smart contract permissioning

### ISSUE THREAD

**Issue by jordy25519** [plugblockchain/plug-blockchain#32]
Provide initial trait and hooks for smart contract permissioning

- [x] Augment the `DelegatedDispatchVerifier` trait
It should provide functions to handle the following call scenarios:
- runtime calls contract
`verify_runtime_to_contract_dispatch(caller, doughnut, contract address) -> Result`

- contract calls contract
`verify_contract_to_contract_dispatch(caller, doughnut, contract address) -> Result`

- [x] Implement the hook for runtime to contract dispatch (`<T as system::Trait>::DelegatedDispatchVerifier>::verify_runtime_to_contract_call`)
https://github.com/plugblockchain/plug-blockchain/blob/b93e3585eb9bb9f1648a0d155e67832a8aa7f30c/srml/contracts/src/lib.rs#L570-L579

**Comment by aliXsed** [comment]
The following commit completed the task: https://github.com/plugblockchain/plug-blockchain/commit/d5cbf41666a6c7cccbda06d8b7b8d9d8d51747d3
