### ISSUE TITLE
Make GA asset info queryable from the chain

### ISSUE THREAD

**Issue by aliXsed** [plugblockchain/plug-blockchain#92]
Update GA module with a new storage map key: asset ID → value: {symbol, ID, dp}

Required fields:

- symbol (characters: A-Z, length: 8) *ignore uniqueness for now, assets are created by governance, unlikely to allow duplicates
- ID
- decimal places (hardcode to 4dp for now, as customising this has other implications)

GA create call should take this metadata also

**Comment by jordy25519** [comment]
closed via #93
